### ISSUE TITLE
how to set expiration time for CreateBuyOrder 

### ISSUE THREAD

**Issue by CodingKittyreal** [YosephKS/moralis-opensea-plugins#1]
After creating a bid-offer i want it to have it expire automatically after a set given time like a normal bid offer on opensea. but nothing i add to code seems to work, can you help me please!!! I am stuck at this for days now. I am really grateful for your time and efforts, Thanks YosephKS you are the best.

**Comment by YosephKS** [comment]
Hey @anaswahab, sorry for the late reply! Appreciate your nice words ❤️ for expiration though it seems that it is only available when you are doing a declining dutch auctions using Moralis Opensea plugin and for normal bid need to cancel it manualy, cheers~
